version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    image: node:20-alpine      # no build, just use the official Node image
    working_dir: /app
    volumes:
      - ./order-api:/app       # mount your Nest source in
      - /app/node_modules      # keep container node_modules
    command: sh -c "npm ci && npm run start:dev"
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb
      RABBITMQ_URL:   amqp://guest:guest@rabbitmq:5672
      REDIS_URL:      redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started

  frontend:
    build: ./frontend
    volumes:
      # 1) bind the host code in first
      - ./frontend:/app
      # 2) then overlay the node_modules volume on top of /app/node_modules
      - frontend_node_modules:/app/node_modules            
    ports:
      - "3000:5173"     # Vite default port is 5173
    depends_on:
      - api
volumes:
  frontend_node_modules: